//! End-to-end integration tests for the openssl-shim scenarios: the
//! RSA DKIM key step exits 1 when `openssl genpkey` fails (a broken
//! shim, a broken binary, missing entropy), and the run completes when
//! the shim produces a real PEM. Lifted into a sibling so
//! `init_end_to_end.rs` stays under the per-file line limit.

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

fn binary() -> &'static Path {
	Path::new(env!("CARGO_BIN_EXE_epistle"))
}

fn write_answers(dir: &Path, name: &str, body: &str) -> PathBuf {
	let path = dir.join(name);
	std::fs::write(&path, body).expect("write answers");
	path
}

/// `openssl` is on `PATH` but the actual `genpkey` call fails (broken
/// binary, missing entropy, broken shim): the run must exit 1 with a
/// report that names the ed25519 key that did land, and the config on
/// disk must NOT carry `rsa_selector` because no RSA key was produced.
/// The previous shape pushed a `Skipped` step, wrote the config with
/// the RSA fields omitted, and exited 0: the operator asked for the
/// key, the key did not land, and the command said everything is fine.
///
/// The shim lives in a tempdir, exits 0 for `openssl version` and
/// non-zero for everything else. Prepending the tempdir to `PATH` for
/// the duration of the run makes the apply phase see an `openssl` it
/// can probe but cannot use.
#[cfg(unix)]
#[test]
fn init_exits_one_when_openssl_genpkey_fails_and_carries_no_rsa_selector() {
	let dir = tempfile::tempdir().expect("tempdir");
	let shim_dir = dir.path().join("bin");
	std::fs::create_dir(&shim_dir).expect("mkdir shim dir");
	let shim_path = shim_dir.join("openssl");
	let shim_body = "#!/bin/sh\n\
		case \"$1\" in\n\
		\tversion)\n\
		\t\techo \"OpenSSL 99.9.9 (test shim)\"\n\
		\t\texit 0\n\
		\t\t;;\n\
	\t*)\n\
		\t\techo \"shim: $@ refused\" >&2\n\
		\t\texit 1\n\
		\t\t;;\n\
	\tesac\n";
	std::fs::write(&shim_path, shim_body).expect("write shim");
	std::fs::set_permissions(&shim_path, std::fs::Permissions::from_mode(0o755))
		.expect("chmod 0755 on shim");

	let data_dir = dir.path().join("data");
	let config_path = dir.path().join("mail.toml");
	let body = format!(
		"mode = \"manual\"\n\
		 hostname = \"mail.example.org\"\n\
		 domains = [\"example.org\"]\n\
		 data_dir = \"{}\"\n\
		 config_path = \"{}\"\n",
		data_dir.display(),
		config_path.display(),
	);
	let answers = write_answers(dir.path(), "answers.toml", &body);
	let system_path = std::env::var_os("PATH").unwrap_or_default();
	let combined_path = {
		let mut p = shim_dir.as_os_str().to_owned();
		if !system_path.is_empty() {
			p.push(":");
			p.push(&system_path);
		}
		p
	};
	let mut cmd = Command::new(binary());
	cmd.args(["init", "--answers", answers.to_str().unwrap()]);
	cmd.env("PATH", &combined_path);
	cmd.stdin(Stdio::null())
		.stdout(Stdio::piped())
		.stderr(Stdio::piped());
	let output = cmd.output().expect("spawn epistle");
	assert_eq!(
		output.status.code(),
		Some(1),
		"genpkey failure must surface as exit code 1; stderr: {}",
		String::from_utf8_lossy(&output.stderr)
	);
	let stderr = String::from_utf8_lossy(&output.stderr);
	assert!(
		stderr.contains("wrote:") && stderr.contains("s1.pem"),
		"the rendered report must name the ed25519 key that landed: {stderr}"
	);
	assert!(
		stderr.contains("RSA") || stderr.contains("openssl"),
		"the rendered error must name the RSA failure: {stderr}"
	);
	let keys_dir = data_dir.join("keys");
	assert!(
		keys_dir.join("s1.pem").exists(),
		"s1.pem must be on disk from the step that ran before the failure"
	);
	assert!(
		!keys_dir.join("s2.pem").exists(),
		"s2.pem must NOT be on disk because generation failed"
	);
	if config_path.exists() {
		let rendered = std::fs::read_to_string(&config_path).expect("read config");
		assert!(
			!rendered.contains("rsa_selector"),
			"the config must NOT carry rsa_selector when RSA generation failed: {rendered}"
		);
		assert!(
			!rendered.contains("rsa_key_file"),
			"the config must NOT carry rsa_key_file when RSA generation failed: {rendered}"
		);
	}
}

/// Acceptance pairing of `init_exits_one_when_openssl_genpkey_fails`:
/// the shim succeeds on every subcommand, the run completes, the
/// config carries `rsa_selector`, and exit code is 0. A rejection
/// test is only worth as much as the acceptance test of the same
/// shape next to it: without this one, a run that always failed
/// would satisfy the pair above.
#[cfg(unix)]
#[test]
fn init_succeeds_and_writes_rsa_selector_when_openssl_shim_succeeds() {
	let dir = tempfile::tempdir().expect("tempdir");
	let shim_dir = dir.path().join("bin");
	std::fs::create_dir(&shim_dir).expect("mkdir shim dir");
	let shim_path = shim_dir.join("openssl");
	// A valid PKCS#8 RSA-2048 PEM, generated by the system openssl
	// once and pasted here. The shim returns this verbatim so the
	// apply phase can land s2.pem and the config.
	let pem = "-----BEGIN PRIVATE KEY-----\n\
		MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQHkSMffG5t9A9\n\
		opH2mx1f47JZ+6poa15MZO1dxAVvsVON+pmeq+QPybbBsrjBkaQHAgKS1mM7Hz4d\n\
		E71irZvIE3Y0SjawntQ3zoXxz4o+UjmSJWKyRNdlc0neiiBy7pckNyMXziv/lTuR\n\
		62hlf6XoZMXMnW8fx9JgIHzLLKGSh/JNRErPIotfXkxIrhDrSpHLtdrvweS07uaU\n\
		DOTf6vHNz6wzC8k9nxLGR4AlKPiLhbR/NnBO9LHGXlzqs2K2UugO6/TuTMKFNlNh\n\
		oXVwpjDQZfhN7u6qSBd8u5ujnXajGTN1EOtoFvuz+z8rShCxhESZ4ew/micd0hA2\n\
		e6KzrMavAgMBAAECggEAALxxs3lUceV2KhTL5UeRYs2Lz7hskSox35HBNlPL/9pV\n\
		Rfm5pm9nDqIWRb57KSUz/LMGaJu7Tapd6Xd6Ndc/NPJWQFikPybciyVxYwXqpIxN\n\
		kldpimzRVW57bf74MkLIDQN74bOByVUrUy3okZr4/h4GtMYwoLf7cX5a9Bj00K17\n\
		DvkMLKLHyzBSbmNOg2likcyV7oSHyuYQMBhK8K003Flq6yiK4gc/4WKMoUTbDQRp\n\
		7Q948YvwWLX1NaOzNDzSXBv0hIXAj/5BeOQHFFIXcVgrViseBKtT6CcEM7nVukjM\n\
		T9PvsmqGEAdpe8aOPoDrNKoXH5h22KT7xgchIrXv/QKBgQDtaaGZskvhXuQiQOuk\n\
		nwtPtyeGfEmA4Cuov0KvSOVGwLPDp5n/W/WS7hv8ye5GD5G8/OIQ63l9+7U60hvo\n\
		wwgxFlBXzoHsWofiIGfFhWtJ1g5PeSzdSp9kybQ7avrRmFCXTt9E4ZwF8TEaxjzM\n\
		dLF1bYKX0+zFlexYwx0Z97uGtQKBgQDgaYAgQJSHZfg7noel9Aq8pdQvyrEOmptj\n\
		Vu2T8sq+O5IVQVwXIIQZ7NAERKfLm2q3rxo4etHqCL0zV0G5gTXf9bu8MFg0XvSk\n\
		f0WZx/f65OJLVpucHAbFchJpwlu7FPIV5OUeh+j0HPV74sILzF1DICo4CWhA9xwO\n\
		UQXebwXyUwKBgCSF1Yhxd17qXCow1o9ysCjJQllcEWq0EcNZ+QZCLpNd3cnBpN01\n\
		5md+HewbnH5GsuLh/F0h/IS3DkBIRmbeagozJpT7fd1AaBsPZSdryP+I4Ja1S4OX\n\
		kUHODd3+LSvFRNCiH5LXKkt3uVgnGv9RDGPGPwrgXVJgKAXXrkhqZfzpAoGBALXs\n\
		sSL0V7SgNKnYba1adu3SHX8U+Y6WRcw1p2oeFMA9OMMkdkyFXrJJqaUcJ09HUi9Q\n\
		s5f/8Xah2Qfq/+wr1IoYAzaflpH2PKuyRbFSTDVIIi/jKUlX6yFbxZOZLZYvd8XK\n\
		BvhGQ9LKOzRQcvDvnteRFsjQz4SDD2qHwpM9O/vjAoGAd/6+y68FmpzQvdZCSgQI\n\
		jIXgv79Y2MoqLl11nV6LDPmmTH4x5JuFq3DouLp64XZLmWBgL3q4F8QUTd3unjJB\n\
		drRyxQ/H75sKsFe1cJo4GlYgXJ2o/ontR0+Ze6Je3VslVDJsS59oPI2PGI4ooO6x\n\
		Z/w5QU72iad6bnEm/fLLql4=\n\
		-----END PRIVATE KEY-----\n";
	let shim_body = format!(
		"#!/bin/sh\n\
		 case \"$1\" in\n\
		 \tversion)\n\
		 \t\techo \"OpenSSL 99.9.9 (test shim)\"\n\
		 \t\texit 0\n\
		 \t\t;;\n\
		 \tgenpkey)\n\
		 \t\tcat <<'PEM'\n{pem}PEM\n\
		 \t\texit 0\n\
		 \t\t;;\n\
		 \t*)\n\
		 \t\texit 1\n\
		 \t\t;;\n\
		 esac\n"
	);
	std::fs::write(&shim_path, shim_body).expect("write shim");
	std::fs::set_permissions(&shim_path, std::fs::Permissions::from_mode(0o755))
		.expect("chmod 0755 on shim");

	let data_dir = dir.path().join("data");
	let config_path = dir.path().join("mail.toml");
	let body = format!(
		"mode = \"manual\"\n\
		 hostname = \"mail.example.org\"\n\
		 domains = [\"example.org\"]\n\
		 data_dir = \"{}\"\n\
		 config_path = \"{}\"\n",
		data_dir.display(),
		config_path.display(),
	);
	let answers = write_answers(dir.path(), "answers.toml", &body);
	let system_path = std::env::var_os("PATH").unwrap_or_default();
	let combined_path = {
		let mut p = shim_dir.as_os_str().to_owned();
		if !system_path.is_empty() {
			p.push(":");
			p.push(&system_path);
		}
		p
	};
	let mut cmd = Command::new(binary());
	cmd.args(["init", "--answers", answers.to_str().unwrap()]);
	cmd.env("PATH", &combined_path);
	cmd.stdin(Stdio::null())
		.stdout(Stdio::piped())
		.stderr(Stdio::piped());
	let output = cmd.output().expect("spawn epistle");
	assert!(
		output.status.success(),
		"apply must succeed when the shim produces a key; exit: {:?}; stderr: {}",
		output.status,
		String::from_utf8_lossy(&output.stderr)
	);
	let keys_dir = data_dir.join("keys");
	assert!(
		keys_dir.join("s2.pem").exists(),
		"s2.pem must be on disk when the shim succeeds"
	);
	assert!(
		config_path.exists(),
		"the config must have been written when the shim succeeds"
	);
	let rendered = std::fs::read_to_string(&config_path).expect("read config");
	assert!(
		rendered.contains("rsa_selector"),
		"the config must carry rsa_selector when the RSA key was produced: {rendered}"
	);
}
