//! Parser inputs and explicit delegation decisions for every command.

pub(super) const CASES: &[(&[&str], bool)] = &[
	(
		&[
			"mta-sts-serve",
			"--policy-dir",
			"/tmp/policy",
			"--cert",
			"/tmp/cert",
			"--key",
			"/tmp/key",
		],
		false,
	),
	(&["serve"], false),
	(&["config-check"], true),
	(&["dkim-keygen", "--out", "/tmp/dkim.pem"], false),
	(&["storage-keygen"], false),
	(&["oauth-keygen"], false),
	(&["export", "--account", "alice"], true),
	(&["import", "--account", "alice"], true),
	(&["backup"], true),
	(&["restore"], true),
	(&["verify"], true),
	(&["verify-dns"], true),
	(&["dns-records"], true),
	(&["mobileconfig", "--account", "alice"], true),
	(&["srv-records"], true),
	(&["autoconfig"], true),
	(&["autodiscover"], true),
	(&["suppression"], true),
	(&["report-abuse"], true),
	(&["accounts"], true),
	(
		&[
			"account-add",
			"--name",
			"alice",
			"--address",
			"alice@example.org",
		],
		true,
	),
	(
		&["account-remove", "--name", "alice", "--queue", "discard"],
		true,
	),
	(&["queue"], true),
	(&["token-hash"], false),
	(
		&[
			"app-password-create",
			"--account",
			"alice",
			"--label",
			"phone",
		],
		true,
	),
	(&["app-passwords"], true),
	(
		&[
			"app-password-revoke",
			"--account",
			"alice",
			"--label",
			"phone",
		],
		true,
	),
	(
		&["api-key-create", "--label", "ci", "--scope", "read"],
		true,
	),
	(&["api-keys"], true),
	(&["api-key-revoke", "--label", "ci"], true),
	(&["archive", "list", "alice"], true),
	(
		&[
			"archive",
			"restore",
			"alice",
			"00000000-0000-0000-0000-000000000000",
		],
		true,
	),
	(&["archive", "purge", "alice"], true),
	(&["reports"], true),
	(&["local", "--dir", "/tmp/local"], false),
	(&["init"], true),
	(&["stack", "ps"], true),
];
