//! Refresh only the generated mail image; operator image pins remain untouched.

use std::io;
use std::path::Path;

pub(super) fn rewrite_default_image(compose: &Path) -> io::Result<()> {
	let bytes = std::fs::read(compose)?;
	let mut value: serde_json::Value = serde_json::from_slice(&bytes)
		.map_err(|_| io::Error::other("compose must be the JSON file generated by epistle init"))?;
	let image = value
		.pointer("/services/mail/image")
		.and_then(serde_json::Value::as_str)
		.ok_or_else(|| io::Error::other("compose has no mail image"))?;
	let managed = match value.get("x-epistle-managed-image") {
		Some(flag) => flag.as_bool() == Some(true),
		// Older init releases used a floating major.minor tag without ownership metadata.
		None => legacy_default(image),
	};
	let default = super::init::default_image();
	if !managed || image == default {
		return Ok(());
	}
	value["services"]["mail"]["image"] = default.into();
	value["x-epistle-managed-image"] = true.into();
	let mut rendered = serde_json::to_vec_pretty(&value)?;
	rendered.push(b'\n');
	crate::storage::write_secret(compose, &rendered)
}

fn legacy_default(image: &str) -> bool {
	let Some(tag) = image.strip_prefix("ghcr.io/glyndor/epistle:") else {
		return false;
	};
	let parts: Vec<_> = tag.split('.').collect();
	parts.len() == 2
		&& parts
			.iter()
			.all(|part| !part.is_empty() && part.bytes().all(|b| b.is_ascii_digit()))
}

#[cfg(test)]
#[path = "stack_update_tests.rs"]
mod tests;
