[package]
name = "epistle-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
epistle = { path = ".." }

[[bin]]
name = "smtp_command"
path = "fuzz_targets/smtp_command.rs"
test = false
doc = false
bench = false

[[bin]]
name = "smtp_line"
path = "fuzz_targets/smtp_line.rs"
test = false
doc = false
bench = false

[[bin]]
name = "smtp_address"
path = "fuzz_targets/smtp_address.rs"
test = false
doc = false
bench = false

[[bin]]
name = "imap_command"
path = "fuzz_targets/imap_command.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sieve_message"
path = "fuzz_targets/sieve_message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sieve_script"
path = "fuzz_targets/sieve_script.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pop3_command"
path = "fuzz_targets/pop3_command.rs"
test = false
doc = false
bench = false

[[bin]]
name = "managesieve_command"
path = "fuzz_targets/managesieve_command.rs"
test = false
doc = false
bench = false

# Detach from the parent crate's workspace.
[workspace]
