//! Per-account masked email addresses (RFC 8058 §3-style disposable aliases).
//!
//! A masked address is a server-generated, throwable address of the form
//! `<label-slug>.<8 base32 chars>@<account domain>`. The label is supplied by
//! the user (for human readability); the random suffix is generated by the
//! server from the CSPRNG so it cannot be guessed, and the full address is
//! chosen by the server — never the client — to avoid collisions with real
//! accounts and predictable enumeration.
//!
//! Each masked address has an owner account, an `enabled` flag, a
//! `created_at` timestamp and a `last_used_at` timestamp the delivery path
//! bumps best-effort. Disabling an address makes it reject exactly like an
//! unknown user; a disabled mask never reveals that it once existed.
//!
//! Persistence mirrors [`super::app_passwords`]: a single JSON file under
//! `{data_dir}/masked.json`, written atomically with owner-only (`0600`)
//! permissions.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use super::StoreError;

/// A single masked email address entry as persisted in `masked.json`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct MaskedAddress {
	/// The full generated address (`label.<8 random base32 chars>@domain`).
	pub address: String,
	/// Owning account name (lowercased).
	pub account: String,
	/// Human-readable label (the user-supplied part, slugified).
	pub label: String,
	/// Creation time as epoch seconds.
	pub created_at: u64,
	/// Whether delivery and send-as are currently allowed. `false` rejects the
	/// address with the same response an unknown user gets.
	pub enabled: bool,
	/// Last time the address received a successfully delivered message, as
	/// epoch seconds. `None` until first use.
	#[serde(default)]
	pub last_used_at: Option<u64>,
}

/// The on-disk JSON document: every masked address keyed by lowercased
/// address (so lookups are case-insensitive and idempotent).
#[derive(Debug, Default, Serialize, Deserialize)]
struct MaskedFile {
	#[serde(default)]
	addresses: HashMap<String, MaskedAddress>,
}

/// Filesystem-backed store of masked email addresses.
pub struct MaskedAddressStore {
	path: PathBuf,
	/// All entries, keyed by lowercased address.
	entries: HashMap<String, MaskedAddress>,
	/// Per-account limit; `0` means no limit. Set via [`Self::with_max_per_account`].
	max_per_account: usize,
}

impl MaskedAddressStore {
	/// Open (loading if present) the store under `data_dir`. A missing file is
	/// an empty store.
	pub fn open(data_dir: &Path) -> Result<Self, StoreError> {
		let path = data_dir.join("masked.json");
		let entries = match std::fs::read_to_string(&path) {
			Ok(text) => {
				let file: MaskedFile = serde_json::from_str(&text)
					.map_err(|error| StoreError::Invalid(error.to_string()))?;
				file.addresses
			}
			Err(error) if error.kind() == std::io::ErrorKind::NotFound => HashMap::new(),
			Err(error) => return Err(error.into()),
		};
		Ok(Self {
			path,
			entries,
			max_per_account: 0,
		})
	}

	/// Override the per-account limit (0 = unlimited). The limit is enforced
	/// by [`Self::add`]; existing entries above the new limit are not pruned.
	pub fn with_max_per_account(mut self, max: usize) -> Self {
		self.max_per_account = max;
		self
	}

	/// Set the per-account limit at runtime (0 = unlimited). For the
	/// builder form, see [`Self::with_max_per_account`].
	pub fn set_max_per_account(&mut self, max: usize) {
		self.max_per_account = max;
	}

	/// The configured per-account limit (0 = unlimited).
	pub fn max_per_account(&self) -> usize {
		self.max_per_account
	}

	/// Every `(address, account)` for the entries, for attaching to the
	/// rebuilt [`crate::smtp::directory::Directory`].
	pub fn entries(&self) -> impl Iterator<Item = (String, String)> + '_ {
		self.entries
			.values()
			.filter(|entry| entry.enabled)
			.map(|entry| (entry.address.clone(), entry.account.clone()))
	}

	/// Look up an entry by lowercased address.
	pub fn get(&self, address: &str) -> Option<&MaskedAddress> {
		self.entries.get(&address.to_ascii_lowercase())
	}

	/// Every entry for an account (lowercased lookup), as the public
	/// list-view rows: `(address, label, enabled, created_at, last_used_at)`.
	/// Sorted by creation time so the listing is stable across calls.
	pub fn list_for_account(&self, account: &str) -> Vec<MaskedAddressView> {
		let mut rows: Vec<MaskedAddressView> = self
			.entries
			.values()
			.filter(|entry| entry.account == account.to_ascii_lowercase())
			.map(MaskedAddressView::from)
			.collect();
		rows.sort_by(|a, b| {
			a.created_at
				.cmp(&b.created_at)
				.then(a.address.cmp(&b.address))
		});
		rows
	}

	/// Generate a fresh masked address for `account` (lowercased) with the
	/// user-supplied `label` (any string), persist it, and return the new
	/// entry. Rejects when the per-account limit would be exceeded, when the
	/// label cannot be slugified into something safe to embed in an address,
	/// or when no `domain` is available. The random suffix comes from the
	/// CSPRNG — never the clock, never the request — so addresses are not
	/// guessable.
	pub fn add(
		&mut self,
		account: &str,
		label: &str,
		domain: &str,
		now: u64,
	) -> Result<MaskedAddress, StoreError> {
		let account = account.to_ascii_lowercase();
		if account.is_empty() {
			return Err(StoreError::Invalid("account is empty".to_string()));
		}
		if domain.is_empty() {
			return Err(StoreError::Invalid("domain is empty".to_string()));
		}
		let slug = slugify_label(label);
		if slug.is_empty() {
			return Err(StoreError::Invalid(
				"label must contain at least one alphanumeric character".to_string(),
			));
		}
		if self.max_per_account > 0 {
			let current = self
				.entries
				.values()
				.filter(|entry| entry.account == account)
				.count();
			if current >= self.max_per_account {
				return Err(StoreError::LimitReached {
					max: self.max_per_account,
				});
			}
		}
		// The CSPRNG generates the suffix; we retry on the (vanishingly
		// unlikely) collision with an existing address so the caller cannot
		// tell whether a collision happened — same outcome either way.
		let mut entry = self.fresh_entry(&account, &slug, label, domain, now)?;
		if self.entries.contains_key(&entry.address) {
			entry = self.fresh_entry(&account, &slug, label, domain, now)?;
			if self.entries.contains_key(&entry.address) {
				return Err(StoreError::Invalid(
					"cannot generate a unique masked address".to_string(),
				));
			}
		}
		self.entries.insert(entry.address.clone(), entry.clone());
		self.persist()?;
		Ok(entry)
	}

	/// Build a fresh [`MaskedAddress`] with a new random suffix. The address
	/// itself is generated from the CSPRNG; callers check uniqueness against
	/// the in-memory map (and retry via this same function on collision).
	fn fresh_entry(
		&self,
		account: &str,
		slug: &str,
		label: &str,
		domain: &str,
		now: u64,
	) -> Result<MaskedAddress, StoreError> {
		let suffix = random_suffix()?;
		let address = format!("{slug}.{suffix}@{domain}").to_ascii_lowercase();
		Ok(MaskedAddress {
			address,
			account: account.to_string(),
			label: label.trim().to_string(),
			created_at: now,
			enabled: true,
			last_used_at: None,
		})
	}

	/// Toggle the `enabled` flag on an address owned by `account`. `NotFound`
	/// when the address does not exist or belongs to another account (so the
	/// endpoint never leaks that an address exists for a different account).
	pub fn set_enabled(
		&mut self,
		account: &str,
		address: &str,
		enabled: bool,
	) -> Result<bool, StoreError> {
		let account = account.to_ascii_lowercase();
		let key = address.to_ascii_lowercase();
		let entry = self
			.entries
			.get(&key)
			.filter(|entry| entry.account == account)
			.ok_or_else(|| StoreError::NotFound(format!("{account}/{address}")))?;
		let previous = entry.enabled;
		if previous == enabled {
			return Ok(previous);
		}
		let mut updated = entry.clone();
		updated.enabled = enabled;
		self.entries.insert(key, updated);
		self.persist()?;
		Ok(previous)
	}

	/// Remove an address owned by `account`. `NotFound` when the address does
	/// not exist or belongs to another account.
	pub fn remove(&mut self, account: &str, address: &str) -> Result<(), StoreError> {
		let account = account.to_ascii_lowercase();
		let key = address.to_ascii_lowercase();
		let entry = self
			.entries
			.get(&key)
			.filter(|entry| entry.account == account)
			.ok_or_else(|| StoreError::NotFound(format!("{account}/{address}")))?;
		let entry = entry.clone();
		self.entries.remove(&entry.address);
		self.persist()
	}

	/// Remove every entry owned by `account` (case-insensitive). Returns the
	/// number of entries removed; persists once at the end. Used by
	/// [`crate::directory_store::removal::remove_account`] to drop the
	/// account's whole footprint; persisting in one pass keeps the on-disk
	/// file consistent with the in-memory state when a single account holds
	/// many masks.
	pub fn remove_all_for_account(&mut self, account: &str) -> Result<u32, StoreError> {
		let account = account.to_ascii_lowercase();
		let before = self.entries.len();
		self.entries.retain(|_, entry| entry.account != account);
		let removed = (before - self.entries.len()) as u32;
		if removed > 0 {
			self.persist()?;
		}
		Ok(removed)
	}

	/// Update `last_used_at` to `now` for an enabled address owned by
	/// `account`. Silent no-op when the address is unknown, disabled, or
	/// owned by another account (so the delivery hot path stays
	/// best-effort). Persistence failures are logged and swallowed.
	pub fn touch_last_used(&mut self, account: &str, address: &str, now: u64) {
		let account = account.to_ascii_lowercase();
		let key = address.to_ascii_lowercase();
		let Some(entry) = self
			.entries
			.get(&key)
			.filter(|entry| entry.enabled && entry.account == account)
		else {
			return;
		};
		if entry.last_used_at == Some(now) {
			return;
		}
		let mut updated = entry.clone();
		updated.last_used_at = Some(now);
		self.entries.insert(key, updated);
		if let Err(error) = self.persist() {
			tracing::warn!(
				target: "epistle::directory_store::masked",
				%account,
				%address,
				%error,
				"cannot persist masked-address last_used_at update"
			);
		}
	}

	/// Atomically rewrite the backing JSON file (write-temp-then-rename, mode 0600).
	fn persist(&self) -> Result<(), StoreError> {
		let file = MaskedFile {
			addresses: self.entries.clone(),
		};
		let text = serde_json::to_string_pretty(&file)
			.map_err(|error| StoreError::Invalid(error.to_string()))?;
		crate::storage::write_secret(&self.path, text.as_bytes())?;
		Ok(())
	}
}

/// A row in the API listing — what an account holder sees about their own
/// masks. The plaintext address is included; nothing else (no secrets, no
/// hashes) is exposed.
#[derive(Debug, Clone, Serialize)]
pub struct MaskedAddressView {
	/// The full generated address (`label.<8 base32 chars>@domain`).
	pub address: String,
	/// Human-readable label as the user submitted it.
	pub label: String,
	/// Whether delivery is currently allowed.
	pub enabled: bool,
	/// Creation time as epoch seconds.
	pub created_at: u64,
	/// Last successful delivery, as epoch seconds. `None` until first use.
	#[serde(skip_serializing_if = "Option::is_none")]
	pub last_used_at: Option<u64>,
}

impl From<&MaskedAddress> for MaskedAddressView {
	fn from(entry: &MaskedAddress) -> Self {
		Self {
			address: entry.address.clone(),
			label: entry.label.clone(),
			enabled: entry.enabled,
			created_at: entry.created_at,
			last_used_at: entry.last_used_at,
		}
	}
}

/// Slugify the user-supplied label into the address's local-part prefix.
/// Non-alphanumeric runs collapse to `-`; leading and trailing separators
/// drop. An empty result rejects the call so we never mint `.<suffix>@...`.
fn slugify_label(label: &str) -> String {
	let mut slug = String::with_capacity(label.len());
	let mut last_dash = true;
	for ch in label.chars() {
		if ch.is_ascii_alphanumeric() {
			slug.push(ch.to_ascii_lowercase());
			last_dash = false;
		} else if !last_dash {
			slug.push('-');
			last_dash = true;
		}
	}
	while slug.ends_with('-') {
		slug.pop();
	}
	slug
}

/// Generate an 8-character lowercase base32 suffix from the CSPRNG. 8 chars
/// of base32 = 40 bits = ~1 trillion possibilities per account; well beyond
/// the per-account cap and not enumerable at SMTP rate.
fn random_suffix() -> Result<String, StoreError> {
	use ring::rand::SecureRandom;
	let mut bytes = [0u8; 5];
	ring::rand::SystemRandom::new()
		.fill(&mut bytes)
		.map_err(|error| StoreError::Invalid(format!("cannot generate random suffix: {error}")))?;
	Ok(crate::totp::encode_base32(&bytes).to_ascii_lowercase())
}

#[cfg(test)]
#[path = "masked_tests.rs"]
mod tests;
