name: Supply chain

on:
  push:
    branches: [develop, main]
  pull_request:

permissions:
  contents: read

jobs:
  sbom-and-licenses:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@d5041b038b7d4935e75400dff612962e6fa14893 # v1.21.0
