name: Supply chain

on:
  push:
    branches: [develop, main]
  pull_request:

permissions:
  contents: read

jobs:
  sbom-and-licenses:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@505d78df893bfc2f73261ff285529e6afd46f5ac # v1.9.1
