name: Supply chain

on:
  push:
    branches: [develop, main]
  pull_request:

permissions:
  contents: read

jobs:
  sbom-and-licenses:
    uses: Glyndor/.github/.github/workflows/rust-supply-chain.yml@b78620146d50fdbc552e1b86740e64d114c58f0f # v1.0.0
